Installer: Added validation of OAT.properties to tomcat6 service scripts
This patch updates tomcat6 service scripts introducing the validation
of the new property IR_DIR, placed in file OAT.properties. If the
property is set, the IR will be placed in the given directory, then
if the directory doesn't exist tomcat won't start.

Signed-off-by: Nicola Barresi <nicola.barresi@polito.it>
Signed-off-by: Roberto Sassu <roberto.sassu@polito.it>

diff --git a/Installer/OAT-Appraiser-Configure/service/tomcat6 b/Installer/OAT-Appraiser-Configure/service/tomcat6
--- a/Installer/OAT-Appraiser-Configure/service/tomcat6
+++ b/Installer/OAT-Appraiser-Configure/service/tomcat6
@@ -40,6 +40,16 @@ LOCK='/var/lock/subsys/tomcat';
 start () {
         echo -n $"Starting $PROG: "
 
+        if [ -f /etc/oat-appraiser/OAT.properties ]; then
+                . /etc/oat-appraiser/OAT.properties >> /dev/null 2>&1
+                IR_DIR=$(echo $IR_DIR|tr -d '\r')
+                if [ ! -d $IR_DIR ]; then
+                        echo "Missing directory $IR_DIR"
+                        echo "Unable to start $PROG"
+                        exit 6;
+                fi
+        fi
+
         # start daemon
         daemon $CATALINA_BIN start
         RETVAL=$?
